name: Tests
on: [check_run, pull_request]
jobs:
  run_front_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          cd react-frontend
          npm install
          npm install @types/node@^18 --save-dev
      - name: Execute the tests
        run: |
          cd react-frontend
          npx vitest
  run_back_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install PostgreSQL
        uses: tj-actions/install-postgresql@v3.2.0
        with:
          postgresql-version: 16
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - name: Start PostgreSQL service
        run: sudo service postgresql start
      - name: Create test database and user
        run: |
          sudo -u postgres psql -c "CREATE USER test_user WITH PASSWORD 'test_password' CREATEDB;"
          sudo -u postgres psql -c "CREATE DATABASE test_db OWNER test_user;"
      - name: Install dependencies
        run: |
          cd express-backend
          npm install
          npx prisma generate
      - name: Create .env file
        run: |
          echo "PORT=8181" > express-backend/.env
          echo "DATABASE_URL=postgresql://test_user:test_password@localhost:5432/test_db" >> express-backend/.env
          echo "SECRET=dev_secret" >> express-backend/.env
      - name: Run migrations
        run: |
          cd express-backend
          sudo npx prisma migrate dev
      - name: Execute the tests
        run: |
          cd express-backend
          npm test